{
    "action": "modify",
    "datafield1": "18446744073709551615",
    "datafield2": "0",
    "datafield3": "65",
    "datafield4": "255",
    "event_src.category": "Host security",
    "event_src.fqdn": "win10-work.stand2008.local",
    "event_src.hostname": "win10-work",
    "event_src.subsys": "Microsoft-Windows-Kernel-EventTracing/Analytic",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "Microsoft_Windows_eventlog_Common_EventTracing_14_Provider_has_been_enabled_to_session",
    "importance": "info",
    "msgid": "14",
    "object": "logging",
    "object.name": "sysmondnsetwsession",
    "object.type": "session",
    "status": "success",
    "subject": "application",
    "subject.id": "{1c95126e-7eea-49a9-a3fe-a378b03ddb4d}",
    "subject.state": "enabled",
    "subject.type": "provider",
    "time": "2024-05-02T11:12:26.637Z"
}