{
    "action": "create",
    "event_src.category": "Operating system",
    "event_src.hostname": "msedgewin10",
    "event_src.id": "Microsoft-Windows-Bits-Client",
    "event_src.subsys": "Microsoft-Windows-Bits-Client/Operational",
    "event_src.title": "windows",
    "event_src.vendor": "microsoft",
    "id": "PT_Microsoft_Windows_eventlog_3_Bits_created_job",
    "msgid": "3",
    "object": "task",
    "object.account.domain": "MSEDGEWIN10",
    "object.account.fullname": "MSEDGEWIN10\\IEUser",
    "object.account.name": "IEUser",
    "object.id": "78E48D71-6706-4BEF-BE13-DD6596AECB77",
    "object.name": "C:\\Users\\IEUser\\AppData\\Local\\Temp\\{F1502BD5-ADFF-4123-9C07-0E4B02FCB037}-89.0.4389.82_87.0.4280.66_chrome_updater.exe",
    "object.process.fullpath": "C:\\Program Files (x86)\\Google\\Update\\GoogleUpdate.exe",
    "object.process.id": "2136",
    "object.process.name": "GoogleUpdate.exe",
    "status": "success",
    "time": "2021-03-15T19:01:32.644Z"
}